# Generated by Django 5.2 on 2025-04-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.BooleanField(default=False),
        ),
    ]
